### ISSUE TITLE
Image 

### ISSUE THREAD

**Issue by divyam5-30** [barrycommins/spring-boot-splunk-sleuth-demo#2]
Unable to pull docker image.Getting below error
Pulling demo-application (barrycommins/spring-boot-sleuth-splunk-demo:)...
ERROR: pull access denied for barrycommins/spring-boot-sleuth-splunk-demo, repository does not exist or may require 'docker login'

Also the maven build fails due to below  error
 Building image barrycommins/spring-boot-sleuth-splunk-demo
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:37 min
[INFO] Finished at: 2020-08-25T09:54:42+04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (default) on project spring-boot-sleuth-splunk-demo: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect -> [Help 1]

**Comment by barrycommins** [comment]
Hi, the reason you can't pull the image is that it's not published to Docker Hub, it's locally built when you run a mvn install.

The plugin used to create the image defaults to localhost:2375 to find your Docker daemon.
If yours is running elsewhere, you can set it via the DOCKER_HOST environment variable.

See https://github.com/spotify/docker-maven-plugin#setup

I haven't updated this project in a while, and this is kind of an outdated way of doing things.
I'll update it to use Spring Boot 2.3's native support for building container images, when I have time.

**Comment by barrycommins** [comment]
I've updated to use Spring Boot's maven plugin for building containers.
Running `mvn clean package` will build the image locally, and it can then be run with docker-compose.
